"""№6 user add unique on username

Revision ID: 05e8b19b1aa9
Revises: fd6584667210
Create Date: 2024-12-15 00:31:24.035021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e8b19b1aa9'
down_revision: Union[str, None] = 'fd6584667210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('username-password-unique', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('username-password-unique', 'User', ['username', 'password'])
    # ### end Alembic commands ###
