"""№4 User: added token

Revision ID: 189d4d8dd998
Revises: ad425f2333f1
Create Date: 2024-12-14 23:24:07.387610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189d4d8dd998'
down_revision: Union[str, None] = 'ad425f2333f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('User', sa.Column('auth_token', sa.String(length=100), nullable=False))
    op.create_unique_constraint('username-password-unique', 'User', ['username', 'password'])
    op.create_unique_constraint(None, 'User', ['auth_token'])
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint('username-password-unique', 'User', type_='unique')
    op.drop_column('User', 'auth_token')
    op.drop_column('User', 'username')
    # ### end Alembic commands ###
