"""7 user delete token field

Revision ID: 8845bcd5cd28
Revises: 05e8b19b1aa9
Create Date: 2024-12-15 22:48:00.292793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8845bcd5cd28'
down_revision: Union[str, None] = '05e8b19b1aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_auth_token_key', 'User', type_='unique')
    op.drop_column('User', 'auth_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('auth_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('User_auth_token_key', 'User', ['auth_token'])
    # ### end Alembic commands ###
