"""№3 Refactor columns

Revision ID: ad425f2333f1
Revises: 6c321b642cb8
Create Date: 2024-12-13 20:32:31.603994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad425f2333f1'
down_revision: Union[str, None] = '6c321b642cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Advertisement', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Advertisement', 'updated_at')
    # ### end Alembic commands ###
